PRAGMA foreign_keys = ON;

CREATE TABLE Manager (
    MID INTEGER PRIMARY KEY,
    Name TEXT NOT NULL,
    Salary INTEGER NOT NULL,
    Contact INTEGER NOT NULL,
    Supervisor INTEGER,
    FOREIGN KEY (Supervisor) REFERENCES Manager(MID)
		ON DELETE SET NULL
		ON UPDATE CASCADE
) STRICT;


CREATE TABLE Worker (
	WID INTEGER PRIMARY KEY,
	Name TEXT NOT NULL,
	Salary INTEGER NOT NULL,
	Contact INTEGER NOT NULL,
	Supervisor INTEGER,
	FOREIGN KEY (Supervisor) REFERENCES Manager(MID)
		ON DELETE SET NULL
		ON UPDATE CASCADE
) STRICT;

CREATE TABLE Location (
	Name TEXT PRIMARY KEY,
	Facility TEXT,
	Supervisor INTEGER,
	FOREIGN KEY (Supervisor) REFERENCES Manager(MID)
		ON DELETE SET NULL
		ON UPDATE CASCADE
) STRICT;


CREATE TABLE Activity (
	AID INTEGER PRIMARY KEY,
	Name TEXT NOT NULL,
	startDate TEXT,
	endDate TEXT,
	CHECK (startDate IS NULL OR endDate IS NULL OR endDate>=startDate)
) STRICT;
-- Note that Date should be stored in ISO-8601 format so that it can be easily compared.

CREATE TABLE Company (
	CompanyID INTEGER PRIMARY KEY,
	Name TEXT NOT NULL,
	Address TEXT NOT NULL,
	Contact INTEGER NOT NULL
) STRICT;

CREATE TABLE Task (
	AID INTEGER NOT NULL,
	Name TEXT NOT NULL,
	Equipment TEXT,
--	Chemicals TEXT,
	PRIMARY KEY (AID, Name),
	FOREIGN KEY (AID) REFERENCES Activity(AID)
		ON DELETE CASCADE
		ON UPDATE CASCADE
		DEFERRABLE INITIALLY DEFERRED
);
-- Note that Task Name has been shortend into Name
-- I have set ON DELETE CASCADE on Task
--
-- Update on 20 Nov: Chemicals can have multi-values. 
-- To avoid offending 1NF, we need to create a new relation.
-- Please see P.30 of Lecture 6 slides.

-- New relation:
CREATE TABLE TaskChemicals (
	AID INTEGER NOT NULL,
	TaskName TEXT NOT NULL,
	Chemicals TEXT NOT NULL,
	PRIMARY KEY (AID, TaskName, Chemicals),
	FOREIGN KEY (AID, TaskName) REFERENCES Task(AID, Name)
		ON DELETE CASCADE
		ON UPDATE CASCADE
		DEFERRABLE INITIALLY DEFERRED
) STRICT;

CREATE TABLE Assigned (
	WID INTEGER NOT NULL,
	AID INTEGER NOT NULL,
	TaskName TEXT NOT NULL,
	PRIMARY KEY (WID, AID, TaskName),
	FOREIGN KEY (WID) REFERENCES Worker(WID)
		ON DELETE CASCADE
		ON UPDATE CASCADE
		DEFERRABLE INITIALLY DEFERRED,
	FOREIGN KEY (AID, TaskName) REFERENCES Task(AID, Name)
		ON DELETE CASCADE
		ON UPDATE CASCADE
		DEFERRABLE INITIALLY DEFERRED
) STRICT;

-- Updated 20 Nov:
CREATE TABLE HoldIn (
	AID INTEGER NOT NULL,
	LocationName TEXT NOT NULL,
	PRIMARY KEY (AID, LocationName),
	FOREIGN KEY (AID) REFERENCES Activity(AID)
		ON DELETE CASCADE
		ON UPDATE CASCADE
		DEFERRABLE INITIALLY DEFERRED,
	FOREIGN KEY (LocationName) REFERENCES Location(Name)
		ON DELETE CASCADE
		ON UPDATE CASCADE
		DEFERRABLE INITIALLY DEFERRED
) STRICT;

CREATE TABLE WorkOn (
	AID INTEGER NOT NULL,
	CompanyID INTEGER NOT NULL,
	ContractedPayment INTEGER NOT NULL,
	ContractedTime TEXT NOT NULL,
	PRIMARY KEY (AID, CompanyID),
	FOREIGN KEY (AID) REFERENCES Activity(AID)
		ON DELETE CASCADE
		ON UPDATE CASCADE
		DEFERRABLE INITIALLY DEFERRED,
	FOREIGN KEY (CompanyID) REFERENCES Company(CompanyID)
		ON DELETE CASCADE
		ON UPDATE CASCADE
		DEFERRABLE INITIALLY DEFERRED
) STRICT;